version: "3.9"

services:
  web:
    build: ./web
    ports:
      - "3000:80"
    depends_on:
      - api
    networks:
      - app-network

  api:
    build: ./api
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data
    environment:
      - NODE_ENV=production
    depends_on:
      - worker
    networks:
      - app-network

  worker:
    build: ./worker
    volumes:
      - ./data:/data
    networks:
      - app-network

volumes:
  data:

networks:
  app-network:
    driver: bridge
